name: continuous-integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - uses: actions/cache@v6
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-chrome-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-puppeteer-chrome-
      - run: pnpm dlx puppeteer browsers install chrome
      - run: pnpm knip
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:e2e
        working-directory: extension
