name: release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    if: github.repository == 'ubermanu/roller'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile

      - id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build and attach extension
        if: steps.changesets.outputs.published == 'true'
        run: |
          TAG=$(echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[0].name + "@" + .[0].version')
          rm extensions/roller/web-ext-artifacts -rf
          pnpm --filter @ubermanu/roller zip
          gh release upload "$TAG" extensions/roller/web-ext-artifacts/*.zip
        env:
          GH_TOKEN: ${{ github.token }}
